POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Steve Jobs",
    "number": "123-123"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Larry Bird",
    "number": "696969696",
    "horoscope": "scorpio"
}