POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "123456789"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Larry Bird",
    "number": "696969696",
    "horoscope": "scorpio"
}